### ISSUE TITLE
swift inventory: token expiry

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/dos_connect#12]
Forces:
* Swift, in order to observe object events, requires [middleware](https://docs.openstack.org/swift/latest/development_middleware.html).  This is an intrusive process, as user code needs to be inserted in production swift instances.  

As a result, we can "degrade" and leverage a polling approach and simply loop list the container, detect changes, and sleep.   S3 support using [ec2 credentials](https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/ec2-credentials.html) is an obvious choice on how to accomplish this. 

* Swift, in it's s3 capacity,  does not support [version 2 list objects](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html).  This becomes an issue for very large containers, where without the "start-after" capability, the entire catalog needs to be downloaded, sorted etc.

As a result, we can can [leverage swift's native api](https://github.com/ohsu-comp-bio/dos_connect/blob/docker/dos_connect/apps/inventory/swift_inventory.py#L115-L117), which supports a [marker query](https://docs.openstack.org/python-swiftclient/latest/swiftclient.html#swiftclient.client.get_container) to enable more efficient polling.

* Swift's native client connection supports a [pre-authenticated token](https://docs.openstack.org/python-swiftclient/latest/swiftclient.html#swiftclient.client.Connection)  ( i.e. the results of 'openstack token issue').  This should be more palatable, in that the inventory service does not need to be configured with user/password.  However, there is an issue in that the `default value for expiry is one hour`.  Changing the default expiry appears to be a [system wide change](https://deepakrghuge.wordpress.com/2015/10/06/changing-token-expiration-in-openstack-keystone/).  This differs completely from openstack's ec2 credential approach where the ec2 credentials do not expire unless revoked.

As a result, we can either:
* degrade to a userid/password approach ( will require a setup of a service user )
* **//TODO - need other alternatives**

**Comment by buchanae** [comment]
A service user and the swift native client seems easiest. Managing service passwords for infrastructure is not abnormal. I'm assuming there is only one DOS service running and polling, and a single database (i.e. not a per-user polling loop).

**Comment by bwalsh** [comment]
@buchanae  thanks for feedback.
The service breakdown is:
* 1 webserver 
* 1 client service per observed 'stack'  i.e. 1 for swift, 1 for google, etc.

I've converted over to userid/pass

https://github.com/ohsu-comp-bio/dos_connect/blob/docker/dos_connect/apps/inventory/swift_inventory.py#L101-L120
